# see https://metallb.universe.tf/configuration/_advanced_l2_configuration/
l2Advertisements: {}
  # my-l2-advertisement:
  #   spec:
  #     ...
ipAddressPools: {}
  # my-ip-adress-pool:
  #   spec:
  #     ...